export const ORDER_STATUS = {
  NEW: 'NEW',
  RECEIVED: 'RECEIVED',
  PROCESSING: 'PROCESSING',
  PROCESSED: 'PROCESSED',
  CONFIRMED: 'CONFIRMED',
  PACKAGED: 'PACKAGED',
  SHIPPING: 'SHIPPING',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
};

export const PAYMENT_METHOD = {
  COD: 'COD',
};

export const PAYMENT_STATUS = {
  AWAITING: 'AWAITING',
  PAID: 'PAID',
  CANCELLED: 'CANCELLED,'
}

export const ORDER_ACTIONS = {
  CREATE: 'CREATE',
  ASSIGN: 'ASSIGN',
  REJECT: 'REJECT',
  UPDATE_LINE_ITEM: 'UPDATE-ITEM',
  PROCESS: 'PROCESS',
  CONFIRM: 'CONFIRM',
  PACKAGE: 'PACKAGE',
  SHIPPING: 'SHIPPING',
  CANCEL: 'CANCEL',
  ORDER_COMPLETION: 'COMPLETE',
}