export const ORDER_STATUS = {
  NEW: 'NEW',
  RECEIVED: 'RECEIVED',
  PROCESSING: 'PROCESSING',
  PROCESSED: 'PROCESSED',
  SHIPPING: 'SHIPPING',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
};

export const PAYMENT_METHOD = {
  COD: 'COD',
};

export const PAYMENT_STATUS = {
  AWAITING: 'AWAITING',
  PAID: 'PAID',
  CANCELLED: 'CANCELLED,'
}