# The release pipeline will run only if all jobs in the test pipeline are successful
stages:
    - release

before_script:
  - npm install

publish:
  only:
    - merge_requests
  image: node:14
  stage: release
  script:
    - npx semantic-release