export const TOKEN_EXPIRES_IN_SECONDS = 8640000;

export const MEDICAL_SERVICE = {
  'DOCTOR_AT_HOME': 'DOCTOR_AT_HOME',
  'CLINIC_APPOINTMENT': 'CLINIC_APPOINTMENT',
  'MEDICAL_TEST': 'MEDICAL_TEST'
}


export const ENTITY_TYPE = {
  'PHARMACY': 'PHARMACY',
  'CLINIC': 'CLINIC',
  'HOSPITAL': 'HOSPITAL',
  'LAB': 'LAB'
}

export const ROOT_COMPANY_ID = +process.env.ROOT_COMPANY_ID || 99999;