const CORE_PERMISSIONS = {
  'CREATE_HOSPITAL': 'CREATE_HOSPITAL',
  'UPDATE_HOSPITAL': 'UPDATE_HOSPITAL',
  'UPDATE_HOSPITAL': 'UPDATE_HOSPITAL',
  'DELETE_HOSPITAL': 'DELETE_HOSPITAL',

}

const HOSPITAL_PERMISSIONS = {
}
export default {
  CORE_PERMISSIONS,
  HOSPITAL_PERMISSIONS,
}